### ISSUE TITLE
Would you consider maintaining date-calc?

### ISSUE THREAD

**Issue by priyadarshan** [ruricolist/date-calc#1]
Since date-calc has not been maintained, it has been [removed from quicklisp](https://github.com/quicklisp/quicklisp-projects/issues/1218#issuecomment-266904217), thus losing visibility, a pity, since it is a nice package definitely worth living on.

I am not related to it, beside being a user, but I was wondering if you would consider stepping in as maintainer?

**Comment by ruricolist** [comment]
Sure, no problem. I've opened [an issue](https://github.com/quicklisp/quicklisp-projects/issues/1716) to have it re-added.

**Comment by priyadarshan** [comment]
Thank you so much.

**Comment by priyadarshan** [comment]
It seems it will be included in next release. Congratulations. Thanks also for all the work done!
