### ISSUE TITLE
Italian days of the week name

### ISSUE THREAD

**Issue by cage2** [ruricolist/date-calc#2]
Hello!

I think the italian names of the days of the week are slightly wrong (an accent is missing on some of them), please compare:

https://github.com/ruricolist/date-calc/blob/master/date-calc.lisp#L198

and

https://en.wikipedia.org/wiki/Names_of_the_days_of_the_week#Romance_languages

(first row of the table after the header, the "italian" one).

Hope this helps!
Bye!
C.

**Comment by ruricolist** [comment]
Thanks. Actually all accents were missing, from days, months, and even language names.

**Comment by cage2** [comment]
On Mon, Aug 12, 2019 at 03:12:54PM -0700, Paul M. Rodriguez wrote:

Hi!

> Thanks.

You are welcome!

Bye!
C.
